# HU6 basins
basins = {
    "south platte": "https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco_8/south_platte.json",
    "arkansas":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco_8/arkansas.json",
    "colorado headwaters":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco_8/colorado_headwaters.json",
    "yampa/white/little snake":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco_8/yampa-white-little_snake.json",
    "laramie and north platte":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco_8/laramie_and_north_platte.json",
    "upper_rio_grande":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco_8/upper_rio_grande.json",
    "san miguel/dolores/animas/san juan":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco_8/san_miguel-dolores-animas-san_juan.json",
    "gunnison":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco_8/gunnison.json",
}

# HU8 data
subbains = {
    "animas":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/animas.json",
    "dolores":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/dolores.json",
    "san miguel":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/san_miguel.json",
    "mancos-la_plata":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/mancos-la_plata.json",
    "upper san juan":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/upper_san_juan.json",
    "big thompson":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/big_thompson.json",
    "boulder":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/boulder.json",
    "cache la poudre":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/cache_la_poudre.json",
    "clear":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/clear.json",
    "north fork cache la poudre":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/north_fork_cache_la_poudre.json",
    "saint vrain":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/saint_vrain.json",
    "upper south platte":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/upper_south_platte.json",
    "apishapa":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/apishapa.json",
    "lower arkansas headwaters":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/lower_arkansas_headwaters.json",    
    "upper arkansas headwaters":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/upper_arkansas_headwaters.json",
    "purgatoire":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/purgatoire.json",
    "cucharas & huerfano":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/cucharas_%26_huerfano.json",
    "laramie":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/laramie.json",
    "north platte headwaters":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/north_platte_headwaters.json",
    "elk":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/elk.jsonl",
    "little snake":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/little_snake.json",
    "white":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/white.json",
    "williams fork of the yampa":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/williams_fork_of_the_yampa.json",
    "yampa":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/yampa.json",
    "north fork gunnison":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/north_fork_gunnison.json",
    "surface-kannah":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/surface-kannah.json",
    "uncompahgre":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/uncompahgre.json",
    "uncompahgre plateau":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/uncompahgre_plateau.json",
    "upper gunnison":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/upper_gunnison.json",
    "blue":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/blue.json",
    "colorado/kremmling to glenwood springs":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/colorado-kremmling_to_glenwood_springs.json",
    "eagle":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/eagle.json",
    "muddy":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/muddy.json",
    "plateau":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/plateau.json",
    "roaring fork":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/roaring_fork.json",
    "troublesome":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/troublesome.json",
    "williams fork":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/williams_fork.json",
    "willow":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/willow.json",
    "alamosa":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/alamosa.json",
    "conejos & rio sanantonio":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/conejos_%26_rio_san_antonio.json",
    "costilla":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/costilla.json",
    "culebra & trinchera":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/culebra_%26_trinchera.json",
    "headwaters rio grande":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/headwaters_rio_grande.json",
    "northern san luis valley":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/northern_san_luis_valley.json",
    "sagauche":"https://nwcc-apps.sc.egov.usda.gov/awdb/basin-plots/POR/WTEQ/assocHUCco2_8/sagauche.json",
    "":"",
}
