name: Nightly ML Training

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch:

jobs:
  prepare_ml_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r $GITHUB_WORKSPACE/openFlowML/requirements.txt

    - name: Train Data
      run: python $GITHUB_WORKSPACE/openFlowML/train.py

    - name: Upload ONNX Model as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: lstm-model-onnx
        path: ./lstm_model.onnx
