name: Nightly ML Training

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch:

jobs:
  prepare_ml_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r $GITHUB_WORKSPACE/openFlowML/requirements.txt

    - name: Retrieve and Combine Data
      run: python $GITHUB_WORKSPACE/openFlowML/CombineData.py

    - name: Normalize Combined Data
      run: python $GITHUB_WORKSPACE/openFlowML/normalize_data.py

    - name: Save normalized data as artifact
      uses: actions/upload-artifact@v2
      with:
        name: normalized_data
        path: ${{ env.CSV_FILE_PATH }}


