name: Nightly ML Training

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight

jobs:
  train_ml_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run feature scrape
      run: python /openFlowML/get_flow&temp_csv.py

    - name: Commit and push changes (optional)
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "Automated message: Update trained model [skip ci]"
        git push
