name: Nightly ML Training

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch:


jobs:
  train_ml_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r /openFlowML/requirements.txt

    - name: Run feature scrape
      run: python /openFlowML/get_temp&flow_csv.py
      
    - name: Generate river (station) IDs
      run: python generate_river_ids.py

    - name: Run feature scrape for each river
      run: |
        while read river_id; do
          python /openFlowML/get_temp&flow_csv.py --river_id "$river_id" --output "output_${river_id}.csv"
        done < river_ids.txt
