name: Release Core ML Model

on:
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # This fetches all history for all branches and tags

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        # need this version to work w coremltools :(
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        pip install bump2version tensorflow==2.6.2 keras coremltools typing-extension==4.1.1

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: ml_training.yml
        workflow_conclusion: success
        name: lstm_model_keras_release
        path: ./model

    - name: Determine new version tag
      id: new_version
      run: |
        LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "Current version: $LATEST_TAG"
        NEW_TAG=$(bump2version --current-version $LATEST_TAG patch --dry-run --list | grep 'new_version=' | cut -d= -f2)
        echo "New version: $NEW_TAG"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

    - name: Count unique station IDs
      id: count_station_ids
      run: |
        UNIQUE_STATION_IDS=$(wc -l < .github/site_ids.txt)
        echo "UNIQUE_STATION_IDS=$UNIQUE_STATION_IDS" >> $GITHUB_ENV

   # - name: Convert ONNX Model to Core ML
   #   run: |
   #     python -m coremltools convert ./model/lstm_model.onnx --output-path ./model/lstm_model_${{ env.NEW_TAG }}.mlmodel --input-names 'input' --output-names 'output'

    #  number of timesteps per sample = (historical_flow_timesteps + forecast_temperature_timesteps) = (60+14)=74
    #  5 features per time step: (Min Flow, Max Flow, TMIN, TMAX, date_normalized)
    - name: Convert Model to Core ML
      run: |
        python $GITHUB_WORKSPACE/openFlowML/ml_utils.py ./model/lstm_model.h5 ./model/lstm_model_${{ env.NEW_TAG }}.mlmodel "[None, 74, (${UNIQUE_STATION_IDS} + 5)]"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.NEW_TAG }}
        release_name: Release ${{ env.NEW_TAG }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./model/lstm_model_${{ env.NEW_TAG }}.mlmodel
        asset_name: lstm_model_${{ env.NEW_TAG }}.mlmodel
        asset_content_type: application/octet-stream
