name: Create Release

on:
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
   #if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: ml_training.yml
        workflow_conclusion: success
        name: lstm-model-onnx
        path: ./model

    - name: Semantic Release
      id: semantic_release
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.semantic_release.outputs.release_upload_url }}
        asset_path: ./model/lstm_model.onnx
        asset_name: lstm-model-${{ steps.semantic_release.outputs.new_version }}.onnx
        asset_content_type: application/octet-stream
        
