name: Create Release

on:
  workflow_run:
    workflows: ["Nightly ML Training"]
    types:
      - completed

jobs:
  create_release:
    runs-on: ubuntu-latest
    needs: prepare_ml_data
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download ONNX Model Artifact
      uses: actions/download-artifact@v2
      with:
        name: lstm-model-onnx
        path: ./model

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.semantic_release.outputs.release_upload_url }}
        asset_path: ./model/lstm_model.onnx
        asset_name: lstm-model-${{ steps.semantic_release.outputs.new_version }}.onnx
        asset_content_type: application/octet-stream
